###############################################################################
# Script: Parse pathfindR Enriched Terms from HTML
# Description: This script parses HTML files generated by pathfindR to extract
#              enriched terms tables for GO-BP, GO-CC, and GO-MF gene sets from
#              cell line analysis.
###############################################################################

# Load required libraries
library(rvest)
library(dplyr)
library(readr)

# Define analysis types to process
analysis_types <- c("CellLine")

# Map folder names to gene sets
folder_map <- c("pathfindR_output" = "GO-BP", "pathfindR_output(1)" = "GO-CC", "pathfindR_output(2)" = "GO-MF")

# Function to parse HTML files and save enriched terms as CSV
parse_and_save <- function(analysis_type) {
  message("Parsing enriched terms for: ", analysis_type)

  # Base directory (current directory)
  base_dir <- "Cell_line/Melanoma/Analysis"

  # Process each folder (gene set)
  for (folder in names(folder_map)) {
    html_file <- file.path(base_dir, folder, "enriched_terms.html")

    if (!file.exists(html_file)) {
      message("HTML file not found: ", html_file)
      next
    }

    # Read and parse HTML content
    html_content <- read_html(html_file)
    tables <- html_content %>% html_table()

    if (length(tables) == 0) {
      message("No table found in: ", html_file)
      next
    }

    # Extract the first table (enriched terms)
    enriched_df <- tables[[1]]

    # Standardize column names
    expected_cols <- c(
      "ID", "Term_Description", "Fold_Enrichment", "occurrence",
      "support", "lowest_p", "highest_p", "Up_regulated", "Down_regulated"
    )
    if (ncol(enriched_df) == length(expected_cols)) {
      colnames(enriched_df) <- expected_cols
    } else {
      message("Column mismatch in: ", html_file, " - Found ", ncol(enriched_df), " columns")
      next
    }

    # Define output CSV file path
    csv_name <- paste0(analysis_type, "_", folder_map[folder], "_enriched_terms.csv")
    csv_file <- file.path(base_dir, csv_name)

    # Save table as CSV
    write.csv(enriched_df, csv_file, row.names = FALSE)
    message("Saved: ", csv_file)
  }
}

# Parse HTML files for each analysis type
for (type in analysis_types) {
  parse_and_save(type)
}

message("Parsing complete!")